name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS HomefirstOne;"
          sudo mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'Hffc@123';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';"

      - name: Test MySQL Connection
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -pHffc@123 -e "SHOW DATABASES;"

      - name: Set environment variables from properties file
        id: load-env-vars
        run: |
          while IFS='=' read -r key value; do
            if [[ "$key" && ! "$key" =~ ^# ]]; then
              export_key=$(echo "$key" | tr . _ | tr '[:lower:]' '[:upper:]')
              export "$export_key"="$value"
              echo "Exported $export_key=$value"
            fi
          done < src/main/resources/application-harshit.properties

      - name: Debug environment variables
        run: |
          echo "Spring Datasource URL: $SPRING_DATASOURCE_URL"
          echo "Spring Datasource Username: $SPRING_DATASOURCE_USERNAME"
          echo "Spring Datasource Password: $SPRING_DATASOURCE_PASSWORD"
          echo "Server Port: $SERVER_PORT"
          echo "Is Salesforce Live: $APPLICATION_FLAGS_ISSALESFORCELIVE"
          echo "File Paths: $APPLICATION_PATH_FILES"
          echo "HFO Base URL: $APPLICATION_KEY_HFOBASEURL"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Corretto_jdk/17.0.11-9.1/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Corretto_jdk/17.0.11-9.1/x64
          SPRING_DATASOURCE_URL: ${{ env.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ env.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.SPRING_DATASOURCE_PASSWORD }}
          SERVER_PORT: ${{ env.SERVER_PORT }}
          APPLICATION_FLAGS_ISSALESFORCELIVE: ${{ env.APPLICATION_FLAGS_ISSALESFORCELIVE }}
          APPLICATION_FLAGS_ISSTRICTPRODUCTION: ${{ env.APPLICATION_FLAGS_ISSTRICTPRODUCTION }}
          APPLICATION_FLAGS_ISNOTIFICATIONLIVE: ${{ env.APPLICATION_FLAGS_ISNOTIFICATIONLIVE }}
          APPLICATION_PATH_FILES: ${{ env.APPLICATION_PATH_FILES }}
          APPLICATION_PATH_FILEIDENTIFIERURL: ${{ env.APPLICATION_PATH_FILEIDENTIFIERURL }}
          APPLICATION_PATH_HFOFILEIDENTIFIERURL: ${{ env.APPLICATION_PATH_HFOFILEIDENTIFIERURL }}
          APPLICATION_KEY_HFOBASEURL: ${{ env.APPLICATION_KEY_HFOBASEURL }}
