name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build & Deploy Spring Boot App
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Hffc@123
          MYSQL_DATABASE: HomefirstOne
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      # Step 4: Build the application
      - name: Build the application
        run: |
          ./gradlew clean
          ./gradlew --no-daemon build

      # Step 6: Build Docker Image
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hfo:${{ github.run_number }}

      # Step 7: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 8: Push Docker Image to Docker Hub
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hfo:${{ github.run_number }}

      # Step 9: Deploy to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/hfo:${{ github.run_number }}
            docker run -d --name hfospring -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/hfo:${{ github.run_number }}
