name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build & Deploy Spring Boot App
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Hffc@123
          MYSQL_DATABASE: HomefirstOne
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Build with Gradle
        run: |
          ./gradlew clean build
          mkdir artifacts && cp build/libs/*.jar artifacts
          cd artifacts && ls

      - name: Get current date and time in IST
        id: vars
        run: |
          IST_DATE=$(TZ='Asia/Kolkata' date +'%Y%m%d%H%M%S')
          echo "TAG=$IST_DATE" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/githubcicd:${{ env.TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/githubcicd:${{ env.TAG }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/githubcicd:${{ env.TAG }}
            docker stop mycontainer || true
            docker rm mycontainer || true
            docker run -d --name mycontainer -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/githubcicd:${{ env.TAG }}
