name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build & Deploy Spring Boot App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Load environment variables from properties file
        id: load-env-vars
        run: |
          while IFS='=' read -r key value; do
            if [[ "$key" && ! "$key" =~ ^# ]]; then
              # Convert property name to a valid shell variable name
              # Replace dots with underscores and convert to uppercase
              export_key=$(echo "$key" | tr . _ | tr '[:lower:]' '[:upper:]')
              export "$export_key"="$value"
            fi
          done < src/main/resources/application-harshit.properties

      - name: Check file permissions and content
        run: |
          ls -l src/main/resources/
          cat src/main/resources/application-harshit.properties

      - name: Debug Output
        run: |
          echo "Debugging environment variables..."
          echo "Spring Datasource URL: $SPRING_DATASOURCE_URL"
          echo "Spring Datasource Username: $SPRING_DATASOURCE_USERNAME"
          echo "Spring Datasource Password: $SPRING_DATASOURCE_PASSWORD"
          echo "Server Port: $SERVER_PORT"
          echo "Is Salesforce Live: $APPLICATION_FLAGS_ISSALESFORCELIVE"
          echo "File Paths: $APPLICATION_PATH_FILES"
          echo "HFO Base URL: $APPLICATION_KEY_HFOBASEURL"

      - name: Build the application
        run: |
          ./gradlew clean
          ./gradlew --no-daemon build

      - name: Get current date and time in IST
        id: vars
        run: |
          IST_DATE=$(TZ='Asia/Kolkata' date +'%Y%m%d%H%M%S')
          echo "TAG=$IST_DATE" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/HFOSpring:${{ env.TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/HFOSpring:${{ env.TAG }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/HFOSpring:${{ env.TAG }}
            docker run -d --name hfocontainer -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/HFOSpring:${{ env.TAG }}
